name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.0
  logger: ^2.0.2+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: