name: common
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  go_router: ^12.1.1
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  firebase_core: ^2.24.0
  firebase_dynamic_links: ^5.4.6
  firebase_messaging: ^14.7.6
  local_auth: ^2.1.7
  rxdart: ^0.27.7
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  


flutter:
