name: resources
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.13.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: GreycliffCF
      fonts:
        - asset: assets/fonts/GreycliffCF-Light.ttf
          weight: 300
        - asset: assets/fonts/GreycliffCF-Regular.ttf
          weight: 400
        - asset: assets/fonts/GreycliffCF-Medium.ttf
          weight: 500
        - asset: assets/fonts/GreycliffCF-DemiBold.ttf
          weight: 600
        - asset: assets/fonts/GreycliffCF-Bold.ttf
          weight: 700